### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by iamkaikai** [iyah4888/SIGGRAPH18SSS#11]
Hi,
when I ran the code, it came up with this result:

```
Traceback (most recent call last):
  File "main_hyper.py", line 25, in <module>
    from deeplab_resnet import HyperColumn_Deeplabv2, read_data_list
  File "/Users/xxx/Desktop/machine learning/SIGGRAPH18SSS-master/deeplab_resnet/__init__.py", line 2, in <module>
    from .hc_deeplab import HyperColumn_Deeplabv2
  File "/Users/xxx/Desktop/machine learning/SIGGRAPH18SSS-master/deeplab_resnet/hc_deeplab.py", line 15, in <module>
    from tensorflow.python.keras._impl.keras.initializers import he_normal
ModuleNotFoundError: No module named 'tensorflow.python.keras._impl'
```

any idea?

**Comment by iamkaikai** [comment]
I think it's because I ran on MacOs Mojave. and my tensorflow version is 1.12.0
Still figuring out how to fix this issue

**Comment by iyah4888** [comment]
I'd recommend using the tested tensorflow versions in the "Requirements", document page.
