### ISSUE TITLE
TypeError: __call__() got an unexpected keyword argument 'partition_info'

### ISSUE THREAD

**Issue by max619** [iyah4888/SIGGRAPH18SSS#2]
When trying to run main_hyper.py `python main_hyper.py --data-dir ./samples` got error `TypeError: __call__() got an unexpected keyword argument 'partition_info'`

System:
Windows 10 x64
TensorFlow 1.10 with GPU

Stack trace:
```
Traceback (most recent call last):
  File "main_hyper.py", line 96, in <module>
    model = HyperColumn_Deeplabv2(sess, args)
  File "D:\LLDevelopment\Programming\Python\SIGGRAPH18SSS\deeplab_resnet\hc_deeplab.py", line 90, in __init__
    self.build_model()
  File "D:\LLDevelopment\Programming\Python\SIGGRAPH18SSS\deeplab_resnet\hc_deeplab.py", line 163, in build_model
    full_act1 = tf.nn.relu(lowrank_linear(full_activation, 256, 512, name="linear"))
  File "D:\LLDevelopment\Programming\Python\SIGGRAPH18SSS\deeplab_resnet\hc_deeplab.py", line 40, in lowrank_linear
    weights1 = tf.get_variable("fc_weights1", [input_.get_shape()[-1], dim_bottle], initializer=he_normal())
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1328, in get_variable
    constraint=constraint)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1090, in get_variable
    constraint=constraint)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 435, in get_variable
    constraint=constraint)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 404, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 796, in _get_single_variable
    use_resource=use_resource)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2234, in variable
    use_resource=use_resource)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2224, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2207, in default_variable_creator
    constraint=constraint)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 259, in __init__
    constraint=constraint)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 368, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 780, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
TypeError: __call__() got an unexpected keyword argument 'partition_info'
```

How can we fix it?

**Comment by iyah4888** [comment]
Hi Max619,
We didn't test it with very recent versions of Tensorflow, so I'm not sure whether the changed API raised the issue.
Could you quickly try with the version we have tested, say 1.8 CPU?
PS: Stackoverflow suggested that the issue would be relevant to the initializer API changes.

**Comment by max619** [comment]
@iyah4888, i installed tensorflow 1.8.0, however same exception has occured
![image](https://user-images.githubusercontent.com/26447324/44596821-49ee6400-a7d6-11e8-8780-0f6b2f87be47.png)

**Comment by iyah4888** [comment]
I couldn't find any reason that raised this error. Also, other guys have no problem to run the code as it is. I'm curious whether you resolve this issue.
From stackflows, the initializer would be a matter. Could you retrieve any reason or package conflict that may affect to the he_normal() function call?
Are you working with python >3?

**Comment by iyah4888** [comment]
Since it has been a long time with no activity, this issue is closed.
