### ISSUE TITLE
Checkpoint not loaded. Not able to execute run_extract_feature.sh

### ISSUE THREAD

**Issue by makaveli10** [iyah4888/SIGGRAPH18SSS#20]
Cloned only this repository and downloaded the pre-trained weights from the link mentioned in the repository. Added a sample image and ran the bash script from terminal and got this:

RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
 [*] Loading checkpoints...
 [!] Load failed...
0 Processing ./samples/input_110.png
Traceback (most recent call last):
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value bn4a_branch2a/moving_variance
	 [[Node: bn4a_branch2a/moving_variance/read = Identity[T=DT_FLOAT, _class=["loc:@bn4a_branch2a/moving_variance"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](bn4a_branch2a/moving_variance)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_hyper.py", line 117, in <module>
    cur_embed = model.test(pad_img.eval())
  File "/home/saurabh/Documents/code/soft_segmentation/SIGGRAPH18SSS/deeplab_resnet/hc_deeplab.py", line 346, in test
    embedmap = self.sess.run(self.netcontainer['out_hypcol'], feed_dict=feed)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value bn4a_branch2a/moving_variance
	 [[Node: bn4a_branch2a/moving_variance/read = Identity[T=DT_FLOAT, _class=["loc:@bn4a_branch2a/moving_variance"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](bn4a_branch2a/moving_variance)]]

Caused by op 'bn4a_branch2a/moving_variance/read', defined at:
  File "main_hyper.py", line 98, in <module>
    model = HyperColumn_Deeplabv2(sess, args)
  File "/home/saurabh/Documents/code/soft_segmentation/SIGGRAPH18SSS/deeplab_resnet/hc_deeplab.py", line 90, in __init__
    self.build_model()
  File "/home/saurabh/Documents/code/soft_segmentation/SIGGRAPH18SSS/deeplab_resnet/hc_deeplab.py", line 143, in build_model
    net = DeepLabResNetModel({'data': input_img}, is_training=self.args.is_training, num_classes=self.args.num_classes)
  File "/home/saurabh/Documents/code/soft_segmentation/SIGGRAPH18SSS/kaffe/tensorflow/network.py", line 48, in __init__
    self.setup(is_training, num_classes)
  File "/home/saurabh/Documents/code/soft_segmentation/SIGGRAPH18SSS/deeplab_resnet/model.py", line 113, in setup
    .batch_normalization(is_training=is_training, activation_fn=tf.nn.relu, name='bn4a_branch2a')
  File "/home/saurabh/Documents/code/soft_segmentation/SIGGRAPH18SSS/kaffe/tensorflow/network.py", line 22, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/home/saurabh/Documents/code/soft_segmentation/SIGGRAPH18SSS/kaffe/tensorflow/network.py", line 269, in batch_normalization
    scope=scope)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 592, in batch_norm
    scope=scope)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 384, in _fused_batch_norm
    collections=moving_variance_collections)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 262, in model_variable
    use_resource=use_resource)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 217, in variable
    use_resource=use_resource)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1203, in get_variable
    constraint=constraint)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1092, in get_variable
    constraint=constraint)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 425, in get_variable
    constraint=constraint)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 805, in _get_single_variable
    constraint=constraint)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 213, in __init__
    constraint=constraint)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 356, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 125, in identity
    return gen_array_ops.identity(input, name=name)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2071, in identity
    "Identity", input=input, name=name)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/saurabh/anaconda3/envs/soft_seg/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value bn4a_branch2a/moving_variance
	 [[Node: bn4a_branch2a/moving_variance/read = Identity[T=DT_FLOAT, _class=["loc:@bn4a_branch2a/moving_variance"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](bn4a_branch2a/moving_variance)]]

**Comment by iyah4888** [comment]
It seems that your run failed to load the pretrained model (checkpoint). Please check whether the pretrained model is in a proper place.
As for obtaining the pretrained model, please check carefully the readme page.
Thanks.

**Comment by iyah4888** [comment]
Also, check the version of Tensorflow. We didn't test and does not guarantee to work in other versions than what we have tested (v.1.4 and 1.8).

**Comment by makaveli10** [comment]
@iyah4888 Yeah it worked thanks, but generated a .mat file I was expecting an image. I have couple more questions how to generate the segmented image and after generating the segmented image, How do I change or remove the background. Thanks in Advance.

**Comment by iyah4888** [comment]
There is no standard format for a multi-layer alpha map. That's why the output is in the format of the general "mat".

As mentioned in the paper, our method does not automatically provide what is background and foreground; thus, it should be identified by hand selection of the components. 

Then, you can replace the image components corresponding to those alpha components you selected with your own background, and sum the alphas to get a single layer. While it's a bit hassle to describe in this text, it should be straightforward. 

Please check the paper, how the alpha components of an image consist of. Then, you can easily get the idea.

**Comment by makaveli10** [comment]
Thanks

**Comment by makaveli10** [comment]
@iyah4888 Each pixel in each layer is augmented with an alpha value and sum of those is 1 for each layer. Do i need to write a separate script for hand selecting the components and then replace those image components or make their alpha to 0 to remove the background. THis is the first time I am using matlab. Sorry to bother you for this silly question but I desperately and curiously want to reproduce the results of the paper. Thanks

**Comment by makaveli10** [comment]
Do i need to hand select the components after retrieving the soft segments from SoftSemanticSegmentation function? how to proceed?
